// utils/countries.js
// Comprehensive list of countries that can make payments through Stripe
// Excludes only countries under international sanctions

export const getCountries = () => [
    // North America
    { code: 'US', name: 'United States', hasStates: true, stateLabel: 'State', zipLabel: 'ZIP Code', zipPlaceholder: '10001' },
    { code: 'CA', name: 'Canada', hasStates: true, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: 'K1A 0B1' },
    { code: 'MX', name: 'Mexico', hasStates: true, stateLabel: 'State', zipLabel: 'Postal Code', zipPlaceholder: '01000' },
    
    // Central America & Caribbean
    { code: 'AG', name: 'Antigua and Barbuda', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'BS', name: 'Bahamas', hasStates: false, stateLabel: 'Island', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'BB', name: 'Barbados', hasStates: false, stateLabel: 'Parish', zipLabel: 'Postal Code', zipPlaceholder: 'BB11000' },
    { code: 'BZ', name: 'Belize', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'CR', name: 'Costa Rica', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '10101' },
    { code: 'DM', name: 'Dominica', hasStates: false, stateLabel: 'Parish', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'DO', name: 'Dominican Republic', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '10101' },
    { code: 'SV', name: 'El Salvador', hasStates: false, stateLabel: 'Department', zipLabel: 'Postal Code', zipPlaceholder: '01101' },
    { code: 'GD', name: 'Grenada', hasStates: false, stateLabel: 'Parish', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'GT', name: 'Guatemala', hasStates: false, stateLabel: 'Department', zipLabel: 'Postal Code', zipPlaceholder: '01001' },
    { code: 'HT', name: 'Haiti', hasStates: false, stateLabel: 'Department', zipLabel: 'Postal Code', zipPlaceholder: '6110' },
    { code: 'HN', name: 'Honduras', hasStates: false, stateLabel: 'Department', zipLabel: 'Postal Code', zipPlaceholder: '11101' },
    { code: 'JM', name: 'Jamaica', hasStates: false, stateLabel: 'Parish', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'NI', name: 'Nicaragua', hasStates: false, stateLabel: 'Department', zipLabel: 'Postal Code', zipPlaceholder: '11001' },
    { code: 'PA', name: 'Panama', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'KN', name: 'Saint Kitts and Nevis', hasStates: false, stateLabel: 'Parish', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'LC', name: 'Saint Lucia', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines', hasStates: false, stateLabel: 'Parish', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'TT', name: 'Trinidad and Tobago', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    
    // South America
    { code: 'AR', name: 'Argentina', hasStates: true, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: 'C1002' },
    { code: 'BO', name: 'Bolivia', hasStates: false, stateLabel: 'Department', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'BR', name: 'Brazil', hasStates: true, stateLabel: 'State', zipLabel: 'CEP', zipPlaceholder: '01310-100' },
    { code: 'CL', name: 'Chile', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '8320000' },
    { code: 'CO', name: 'Colombia', hasStates: false, stateLabel: 'Department', zipLabel: 'Postal Code', zipPlaceholder: '110111' },
    { code: 'EC', name: 'Ecuador', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '170150' },
    { code: 'GF', name: 'French Guiana', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '97300' },
    { code: 'GY', name: 'Guyana', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'PY', name: 'Paraguay', hasStates: false, stateLabel: 'Department', zipLabel: 'Postal Code', zipPlaceholder: '1536' },
    { code: 'PE', name: 'Peru', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '15001' },
    { code: 'SR', name: 'Suriname', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'UY', name: 'Uruguay', hasStates: false, stateLabel: 'Department', zipLabel: 'Postal Code', zipPlaceholder: '11100' },
    { code: 'VE', name: 'Venezuela', hasStates: false, stateLabel: 'State', zipLabel: 'Postal Code', zipPlaceholder: '1010' },
    
    // Europe
    { code: 'AL', name: 'Albania', hasStates: false, stateLabel: 'County', zipLabel: 'Postal Code', zipPlaceholder: '1001' },
    { code: 'AD', name: 'Andorra', hasStates: false, stateLabel: 'Parish', zipLabel: 'Postal Code', zipPlaceholder: 'AD500' },
    { code: 'AM', name: 'Armenia', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '0001' },
    { code: 'AT', name: 'Austria', hasStates: false, stateLabel: 'State', zipLabel: 'Postal Code', zipPlaceholder: '1010' },
    { code: 'AZ', name: 'Azerbaijan', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: 'AZ1000' },
    { code: 'BY', name: 'Belarus', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '220000' },
    { code: 'BE', name: 'Belgium', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '1000' },
    { code: 'BA', name: 'Bosnia and Herzegovina', hasStates: false, stateLabel: 'Entity', zipLabel: 'Postal Code', zipPlaceholder: '71000' },
    { code: 'BG', name: 'Bulgaria', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '1000' },
    { code: 'HR', name: 'Croatia', hasStates: false, stateLabel: 'County', zipLabel: 'Postal Code', zipPlaceholder: '10000' },
    { code: 'CY', name: 'Cyprus', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '1000' },
    { code: 'CZ', name: 'Czech Republic', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '110 00' },
    { code: 'DK', name: 'Denmark', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '1000' },
    { code: 'EE', name: 'Estonia', hasStates: false, stateLabel: 'County', zipLabel: 'Postal Code', zipPlaceholder: '10111' },
    { code: 'FI', name: 'Finland', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '00100' },
    { code: 'FR', name: 'France', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '75001' },
    { code: 'GE', name: 'Georgia', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '0101' },
    { code: 'DE', name: 'Germany', hasStates: true, stateLabel: 'State', zipLabel: 'Postal Code', zipPlaceholder: '10115' },
    { code: 'GI', name: 'Gibraltar', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: 'GX11 1AA' },
    { code: 'GR', name: 'Greece', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '100 00' },
    { code: 'HU', name: 'Hungary', hasStates: false, stateLabel: 'County', zipLabel: 'Postal Code', zipPlaceholder: '1011' },
    { code: 'IS', name: 'Iceland', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '101' },
    { code: 'IE', name: 'Ireland', hasStates: false, stateLabel: 'County', zipLabel: 'Eircode', zipPlaceholder: 'D02 X285' },
    { code: 'IT', name: 'Italy', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '00100' },
    { code: 'XK', name: 'Kosovo', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '10000' },
    { code: 'LV', name: 'Latvia', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: 'LV-1001' },
    { code: 'LI', name: 'Liechtenstein', hasStates: false, stateLabel: 'Municipality', zipLabel: 'Postal Code', zipPlaceholder: '9490' },
    { code: 'LT', name: 'Lithuania', hasStates: false, stateLabel: 'County', zipLabel: 'Postal Code', zipPlaceholder: '01001' },
    { code: 'LU', name: 'Luxembourg', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '1111' },
    { code: 'MT', name: 'Malta', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: 'VLT 1000' },
    { code: 'MD', name: 'Moldova', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: 'MD-2001' },
    { code: 'MC', name: 'Monaco', hasStates: false, stateLabel: 'Ward', zipLabel: 'Postal Code', zipPlaceholder: '98000' },
    { code: 'ME', name: 'Montenegro', hasStates: false, stateLabel: 'Municipality', zipLabel: 'Postal Code', zipPlaceholder: '81000' },
    { code: 'NL', name: 'Netherlands', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '1011 AA' },
    { code: 'MK', name: 'North Macedonia', hasStates: false, stateLabel: 'Municipality', zipLabel: 'Postal Code', zipPlaceholder: '1000' },
    { code: 'NO', name: 'Norway', hasStates: false, stateLabel: 'County', zipLabel: 'Postal Code', zipPlaceholder: '0001' },
    { code: 'PL', name: 'Poland', hasStates: false, stateLabel: 'Voivodeship', zipLabel: 'Postal Code', zipPlaceholder: '00-001' },
    { code: 'PT', name: 'Portugal', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '1000-001' },
    { code: 'RO', name: 'Romania', hasStates: false, stateLabel: 'County', zipLabel: 'Postal Code', zipPlaceholder: '010001' },
    { code: 'SM', name: 'San Marino', hasStates: false, stateLabel: 'Municipality', zipLabel: 'Postal Code', zipPlaceholder: '47890' },
    { code: 'RS', name: 'Serbia', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '11000' },
    { code: 'SK', name: 'Slovakia', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '811 01' },
    { code: 'SI', name: 'Slovenia', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '1000' },
    { code: 'ES', name: 'Spain', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '28001' },
    { code: 'SE', name: 'Sweden', hasStates: false, stateLabel: 'County', zipLabel: 'Postal Code', zipPlaceholder: '100 00' },
    { code: 'CH', name: 'Switzerland', hasStates: false, stateLabel: 'Canton', zipLabel: 'Postal Code', zipPlaceholder: '8000' },
    { code: 'UA', name: 'Ukraine', hasStates: false, stateLabel: 'Oblast', zipLabel: 'Postal Code', zipPlaceholder: '01001' },
    { code: 'GB', name: 'United Kingdom', hasStates: false, stateLabel: 'County', zipLabel: 'Postcode', zipPlaceholder: 'SW1A 1AA' },
    { code: 'VA', name: 'Vatican City', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '00120' },
    
    // Asia
    { code: 'AF', name: 'Afghanistan', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '1001' },
    { code: 'BH', name: 'Bahrain', hasStates: false, stateLabel: 'Governorate', zipLabel: 'Postal Code', zipPlaceholder: '317' },
    { code: 'BD', name: 'Bangladesh', hasStates: false, stateLabel: 'Division', zipLabel: 'Postal Code', zipPlaceholder: '1000' },
    { code: 'BT', name: 'Bhutan', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '11001' },
    { code: 'BN', name: 'Brunei', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: 'BS8670' },
    { code: 'KH', name: 'Cambodia', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '12000' },
    { code: 'CN', name: 'China', hasStates: true, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '100000' },
    { code: 'HK', name: 'Hong Kong', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'IN', name: 'India', hasStates: true, stateLabel: 'State', zipLabel: 'PIN Code', zipPlaceholder: '110001' },
    { code: 'ID', name: 'Indonesia', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '10110' },
    { code: 'IQ', name: 'Iraq', hasStates: false, stateLabel: 'Governorate', zipLabel: 'Postal Code', zipPlaceholder: '10001' },
    { code: 'IL', name: 'Israel', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '9100000' },
    { code: 'JP', name: 'Japan', hasStates: true, stateLabel: 'Prefecture', zipLabel: 'Postal Code', zipPlaceholder: '100-0001' },
    { code: 'JO', name: 'Jordan', hasStates: false, stateLabel: 'Governorate', zipLabel: 'Postal Code', zipPlaceholder: '11110' },
    { code: 'KZ', name: 'Kazakhstan', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '050000' },
    { code: 'KW', name: 'Kuwait', hasStates: false, stateLabel: 'Governorate', zipLabel: 'Postal Code', zipPlaceholder: '12000' },
    { code: 'KG', name: 'Kyrgyzstan', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '720000' },
    { code: 'LA', name: 'Laos', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '01000' },
    { code: 'LB', name: 'Lebanon', hasStates: false, stateLabel: 'Governorate', zipLabel: 'Postal Code', zipPlaceholder: '1100' },
    { code: 'MO', name: 'Macao', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'MY', name: 'Malaysia', hasStates: true, stateLabel: 'State', zipLabel: 'Postcode', zipPlaceholder: '50000' },
    { code: 'MV', name: 'Maldives', hasStates: false, stateLabel: 'Atoll', zipLabel: 'Postal Code', zipPlaceholder: '20026' },
    { code: 'MN', name: 'Mongolia', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '14200' },
    { code: 'MM', name: 'Myanmar', hasStates: false, stateLabel: 'State', zipLabel: 'Postal Code', zipPlaceholder: '11111' },
    { code: 'NP', name: 'Nepal', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '44600' },
    { code: 'OM', name: 'Oman', hasStates: false, stateLabel: 'Governorate', zipLabel: 'Postal Code', zipPlaceholder: '111' },
    { code: 'PK', name: 'Pakistan', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '44000' },
    { code: 'PS', name: 'Palestine', hasStates: false, stateLabel: 'Governorate', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'PH', name: 'Philippines', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '1000' },
    { code: 'QA', name: 'Qatar', hasStates: false, stateLabel: 'Municipality', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'SA', name: 'Saudi Arabia', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '11564' },
    { code: 'SG', name: 'Singapore', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '018956' },
    { code: 'KR', name: 'South Korea', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '03000' },
    { code: 'LK', name: 'Sri Lanka', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '00100' },
    { code: 'TW', name: 'Taiwan', hasStates: false, stateLabel: 'County', zipLabel: 'Postal Code', zipPlaceholder: '100' },
    { code: 'TJ', name: 'Tajikistan', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '734000' },
    { code: 'TH', name: 'Thailand', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '10100' },
    { code: 'TL', name: 'Timor-Leste', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'TR', name: 'Turkey', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '34000' },
    { code: 'TM', name: 'Turkmenistan', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '744000' },
    { code: 'AE', name: 'United Arab Emirates', hasStates: false, stateLabel: 'Emirate', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'UZ', name: 'Uzbekistan', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '100000' },
    { code: 'VN', name: 'Vietnam', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '100000' },
    { code: 'YE', name: 'Yemen', hasStates: false, stateLabel: 'Governorate', zipLabel: 'Postal Code', zipPlaceholder: '' },
    
    // Africa
    { code: 'DZ', name: 'Algeria', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '16000' },
    { code: 'AO', name: 'Angola', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'BJ', name: 'Benin', hasStates: false, stateLabel: 'Department', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'BW', name: 'Botswana', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'BF', name: 'Burkina Faso', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'BI', name: 'Burundi', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'CM', name: 'Cameroon', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'CV', name: 'Cape Verde', hasStates: false, stateLabel: 'Island', zipLabel: 'Postal Code', zipPlaceholder: '7600' },
    { code: 'CF', name: 'Central African Republic', hasStates: false, stateLabel: 'Prefecture', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'TD', name: 'Chad', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'KM', name: 'Comoros', hasStates: false, stateLabel: 'Island', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'CG', name: 'Congo', hasStates: false, stateLabel: 'Department', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'CD', name: 'Congo (Democratic Republic)', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'CI', name: "Côte d'Ivoire", hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'DJ', name: 'Djibouti', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'EG', name: 'Egypt', hasStates: false, stateLabel: 'Governorate', zipLabel: 'Postal Code', zipPlaceholder: '11511' },
    { code: 'GQ', name: 'Equatorial Guinea', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'ER', name: 'Eritrea', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'SZ', name: 'Eswatini', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: 'H100' },
    { code: 'ET', name: 'Ethiopia', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '1000' },
    { code: 'GA', name: 'Gabon', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'GM', name: 'Gambia', hasStates: false, stateLabel: 'Division', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'GH', name: 'Ghana', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'GN', name: 'Guinea', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'GW', name: 'Guinea-Bissau', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '1000' },
    { code: 'KE', name: 'Kenya', hasStates: false, stateLabel: 'County', zipLabel: 'Postal Code', zipPlaceholder: '00100' },
    { code: 'LS', name: 'Lesotho', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '100' },
    { code: 'LR', name: 'Liberia', hasStates: false, stateLabel: 'County', zipLabel: 'Postal Code', zipPlaceholder: '1000' },
    { code: 'LY', name: 'Libya', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'MG', name: 'Madagascar', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '101' },
    { code: 'MW', name: 'Malawi', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'ML', name: 'Mali', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'MR', name: 'Mauritania', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'MU', name: 'Mauritius', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'MA', name: 'Morocco', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '10000' },
    { code: 'MZ', name: 'Mozambique', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '1100' },
    { code: 'NA', name: 'Namibia', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '9000' },
    { code: 'NE', name: 'Niger', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '8001' },
    { code: 'NG', name: 'Nigeria', hasStates: true, stateLabel: 'State', zipLabel: 'Postal Code', zipPlaceholder: '100001' },
    { code: 'RW', name: 'Rwanda', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'ST', name: 'São Tomé and Príncipe', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'SN', name: 'Senegal', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '10000' },
    { code: 'SC', name: 'Seychelles', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'SL', name: 'Sierra Leone', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'SO', name: 'Somalia', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: 'JH09010' },
    { code: 'ZA', name: 'South Africa', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '0001' },
    { code: 'SS', name: 'South Sudan', hasStates: false, stateLabel: 'State', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'SD', name: 'Sudan', hasStates: false, stateLabel: 'State', zipLabel: 'Postal Code', zipPlaceholder: '11111' },
    { code: 'TZ', name: 'Tanzania', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '11000' },
    { code: 'TG', name: 'Togo', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'TN', name: 'Tunisia', hasStates: false, stateLabel: 'Governorate', zipLabel: 'Postal Code', zipPlaceholder: '1000' },
    { code: 'UG', name: 'Uganda', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '10101' },
    { code: 'ZM', name: 'Zambia', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '10101' },
    { code: 'ZW', name: 'Zimbabwe', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '' },
    
    // Oceania
    { code: 'AU', name: 'Australia', hasStates: true, stateLabel: 'State/Territory', zipLabel: 'Postcode', zipPlaceholder: '2000' },
    { code: 'FJ', name: 'Fiji', hasStates: false, stateLabel: 'Division', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'KI', name: 'Kiribati', hasStates: false, stateLabel: 'Island', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'MH', name: 'Marshall Islands', hasStates: false, stateLabel: 'Atoll', zipLabel: 'Postal Code', zipPlaceholder: '96960' },
    { code: 'FM', name: 'Micronesia', hasStates: false, stateLabel: 'State', zipLabel: 'Postal Code', zipPlaceholder: '96941' },
    { code: 'NR', name: 'Nauru', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'NZ', name: 'New Zealand', hasStates: false, stateLabel: 'Region', zipLabel: 'Postcode', zipPlaceholder: '1010' },
    { code: 'PW', name: 'Palau', hasStates: false, stateLabel: 'State', zipLabel: 'Postal Code', zipPlaceholder: '96940' },
    { code: 'PG', name: 'Papua New Guinea', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '111' },
    { code: 'WS', name: 'Samoa', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: 'WS1234' },
    { code: 'SB', name: 'Solomon Islands', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'TO', name: 'Tonga', hasStates: false, stateLabel: 'Division', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'TV', name: 'Tuvalu', hasStates: false, stateLabel: 'Island', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'VU', name: 'Vanuatu', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '' },
    
    // Territories and special administrative regions (commonly used for payments)
    { code: 'AS', name: 'American Samoa', hasStates: false, stateLabel: 'District', zipLabel: 'ZIP Code', zipPlaceholder: '96799' },
    { code: 'AW', name: 'Aruba', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'BM', name: 'Bermuda', hasStates: false, stateLabel: 'Parish', zipLabel: 'Postal Code', zipPlaceholder: 'FL 07' },
    { code: 'KY', name: 'Cayman Islands', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: 'KY1-1000' },
    { code: 'CW', name: 'Curaçao', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'FK', name: 'Falkland Islands', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: 'FIQQ 1ZZ' },
    { code: 'FO', name: 'Faroe Islands', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '100' },
    { code: 'GL', name: 'Greenland', hasStates: false, stateLabel: 'Municipality', zipLabel: 'Postal Code', zipPlaceholder: '3900' },
    { code: 'GP', name: 'Guadeloupe', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '97100' },
    { code: 'GU', name: 'Guam', hasStates: false, stateLabel: 'Village', zipLabel: 'ZIP Code', zipPlaceholder: '96910' },
    { code: 'IM', name: 'Isle of Man', hasStates: false, stateLabel: 'Parish', zipLabel: 'Postal Code', zipPlaceholder: 'IM1 1AA' },
    { code: 'JE', name: 'Jersey', hasStates: false, stateLabel: 'Parish', zipLabel: 'Postal Code', zipPlaceholder: 'JE1 1AA' },
    { code: 'MQ', name: 'Martinique', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '97200' },
    { code: 'YT', name: 'Mayotte', hasStates: false, stateLabel: 'Canton', zipLabel: 'Postal Code', zipPlaceholder: '97600' },
    { code: 'NC', name: 'New Caledonia', hasStates: false, stateLabel: 'Province', zipLabel: 'Postal Code', zipPlaceholder: '98800' },
    { code: 'MP', name: 'Northern Mariana Islands', hasStates: false, stateLabel: 'Municipality', zipLabel: 'ZIP Code', zipPlaceholder: '96950' },
    { code: 'PF', name: 'French Polynesia', hasStates: false, stateLabel: 'Subdivision', zipLabel: 'Postal Code', zipPlaceholder: '98700' },
    { code: 'PR', name: 'Puerto Rico', hasStates: false, stateLabel: 'Municipality', zipLabel: 'ZIP Code', zipPlaceholder: '00901' },
    { code: 'RE', name: 'Réunion', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '97400' },
    { code: 'BL', name: 'Saint Barthélemy', hasStates: false, stateLabel: 'Quartier', zipLabel: 'Postal Code', zipPlaceholder: '97133' },
    { code: 'MF', name: 'Saint Martin', hasStates: false, stateLabel: 'Collectivity', zipLabel: 'Postal Code', zipPlaceholder: '97150' },
    { code: 'PM', name: 'Saint Pierre and Miquelon', hasStates: false, stateLabel: 'Commune', zipLabel: 'Postal Code', zipPlaceholder: '97500' },
    { code: 'SX', name: 'Sint Maarten', hasStates: false, stateLabel: 'Region', zipLabel: 'Postal Code', zipPlaceholder: '' },
    { code: 'TC', name: 'Turks and Caicos Islands', hasStates: false, stateLabel: 'Island', zipLabel: 'Postal Code', zipPlaceholder: 'TKCA 1ZZ' },
    { code: 'VI', name: 'U.S. Virgin Islands', hasStates: false, stateLabel: 'District', zipLabel: 'ZIP Code', zipPlaceholder: '00801' },
    { code: 'VG', name: 'British Virgin Islands', hasStates: false, stateLabel: 'District', zipLabel: 'Postal Code', zipPlaceholder: 'VG1110' },
    { code: 'WF', name: 'Wallis and Futuna', hasStates: false, stateLabel: 'Kingdom', zipLabel: 'Postal Code', zipPlaceholder: '98600' }
  ].sort((a, b) => a.name.localeCompare(b.name));
  
  // Export default for backward compatibility
  export default { getCountries };